# Generated by Django 6.0.6 on 2026-07-19 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('medical_houses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmé'), ('CANCELLED', 'Annulé'), ('COMPLETED', 'Terminé'), ('NO_SHOW', 'Absence patient')], default='PENDING', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_cancelled', to=settings.AUTH_USER_MODEL)),
                ('medical_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='medical_houses.medicalhouse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_patient', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_professional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_datetime'],
                'indexes': [models.Index(fields=['professional', 'start_datetime'], name='appointment_profess_32b382_idx'), models.Index(fields=['patient', 'start_datetime'], name='appointment_patient_d6a22a_idx')],
            },
        ),
    ]
