# Generated by Django 6.0.6 on 2026-07-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_medicaldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_24h_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_2h_sent',
            field=models.BooleanField(default=False),
        ),
    ]
