# Generated by Django 6.0.6 on 2026-07-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldocument',
            name='document_type',
            field=models.CharField(choices=[('LAB_RESULT', 'Résultat de prise de sang'), ('REPORT', 'Rapport médical'), ('PRESCRIPTION_KINE', 'Prescription pour kinésithérapeute'), ('PSY_NOTE', 'Note psychologique'), ('OTHER', 'Autre document')], default='OTHER', max_length=20),
        ),
    ]
