# Generated by Django 6.0.6 on 2026-07-23 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField(help_text='Montant en centimes (ex: 2500 = 25,00 EUR).')),
                ('currency', models.CharField(default='eur', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCEEDED', 'Payé'), ('REFUNDED', 'Remboursé'), ('PARTIALLY_REFUNDED', 'Remboursé partiellement'), ('FAILED', 'Échoué')], default='PENDING', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('refunded_amount_cents', models.PositiveIntegerField(default=0)),
                ('late_cancellation_fee_due_cents', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
