# Generated by Django 6.0.6 on 2026-07-27 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LegalGuardianLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents_link', to=settings.AUTH_USER_MODEL)),
                ('minor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_link', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
