# Generated by Django 6.0.6 on 2026-07-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_date_of_birth_legalguardianlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalguardianlink',
            name='attested_on_honour',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legalguardianlink',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
