# Generated by Django 6.0.6 on 2026-07-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_legalguardianlink_attested_on_honour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('USER_CREATED', 'Compte créé'), ('USER_UPDATED', 'Compte modifié'), ('USER_ACTIVATED', 'Compte activé'), ('USER_DEACTIVATED', 'Compte désactivé'), ('PAYMENT_SUCCEEDED', 'Paiement confirmé'), ('PAYMENT_FAILED', 'Paiement échoué'), ('PAYMENT_REFUNDED', 'Paiement remboursé')], max_length=30),
        ),
    ]
