# Generated by Django 6.0.6 on 2026-08-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='health_data_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='health_data_consent_given',
            field=models.BooleanField(default=False),
        ),
    ]
