# Generated by Django 6.0.6 on 2026-08-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_health_data_consent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('USER_CREATED', 'Compte créé'), ('USER_UPDATED', 'Compte modifié'), ('USER_ACTIVATED', 'Compte activé'), ('USER_DEACTIVATED', 'Compte désactivé'), ('PAYMENT_SUCCEEDED', 'Paiement confirmé'), ('PAYMENT_FAILED', 'Paiement échoué'), ('PAYMENT_REFUNDED', 'Paiement remboursé'), ('APPOINTMENT_CREATED_BY_STAFF', 'Rendez-vous créé par le secrétariat'), ('APPOINTMENT_CANCELLED_BY_STAFF', 'Rendez-vous annulé par le secrétariat')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('MEDECIN', 'Médecin généraliste'), ('KINE', 'Kinésithérapeute'), ('PSYCHOLOGUE', 'Psychologue'), ('ADMIN', 'Administrateur'), ('SECRETAIRE', 'Secrétaire')], default='PATIENT', max_length=20),
        ),
    ]
