# Generated by Django 6.0.6 on 2026-07-21 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signe_gravite_immediat', models.BooleanField()),
                ('signe_visible_inquietant', models.BooleanField()),
                ('douleur_intense', models.BooleanField()),
                ('impact_activites_quotidiennes', models.BooleanField()),
                ('depuis_plus_de_3_jours', models.BooleanField()),
                ('orientation', models.CharField(choices=[('REPOS', 'Repos et surveillance'), ('TELECONSULTATION', 'Téléconsultation'), ('CONSULTATION_SUR_PLACE', 'Consultation sur place'), ('URGENCE', 'Urgence — appeler les secours / se rendre aux urgences')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
